---
apiVersion: duplication.k8s.wantedly.com/v1beta1
items:
- apiVersion: duplication.k8s.wantedly.com/v1beta1
  kind: DeploymentCopy
  metadata:
    creationTimestamp: null
    name: some-deployment-copy
    namespace: some-namespace
  spec:
    hostname: ""
    nameSuffix: ""
    replicas: 0
    targetContainers:
    - env: null
      image: another-image-tag
      name: some-container
    targetDeploymentName: some-deployment
  status: {}
kind: DeploymentCopyList
metadata: {}

---
apiVersion: apps/v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: some-app
      role: web
    name: some-deployment
    namespace: some-namespace
  spec:
    selector:
      matchLabels:
        app: some-app
        role: web
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: some-app
          role: web
      spec:
        containers:
        - image: some-image-tag
          name: some-container
          resources: {}
  status: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: some-app
      role: web
    name: some-deployment-some-deployment-copy
    namespace: some-namespace
  spec:
    selector:
      matchLabels:
        app: some-app
        role: web
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: some-app
          role: web
      spec:
        containers:
        - image: other-image-tag
          name: some-container
          resources: {}
  status: {}
kind: DeploymentList
metadata: {}

