# permissions for end users to view deploymentcopies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentcopy-viewer-role
rules:
- apiGroups:
  - duplication.k8s.wantedly.com
  resources:
  - deploymentcopies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - duplication.k8s.wantedly.com
  resources:
  - deploymentcopies/status
  verbs:
  - get
