name: Docker Image Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: quay.io/wantedly/deployment-duplicator:${{ github.sha }}${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && ',quay.io/wantedly/deployment-duplicator:latest' || '' }}
